# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Socket.IO_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Socket.IO_test
  pod 'Socket.IO-Client-Swift'

end
